
import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, FileText, CheckCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function AIServiceEstimator() {
    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);
    const [isOpen, setIsOpen] = useState(false);
    const { toast } = useToast();

    const [formData, setFormData] = useState({
        infrastructure: "",
        users: "",
        dataVolume: "",
        industry: "",
        email: ""
    });

    const [strategy, setStrategy] = useState<any>(null);

    const handleEstimate = async () => {
        setLoading(true);
        try {
            const response = await fetch('/api/ai-strategy-estimate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(formData)
            });
            const data = await response.json();
            setStrategy(data);
            setStep(2);
            toast({
                title: "AI Strategy Ready",
                description: "Your personalized strategy has been generated by Gemini 2.5 Flash.",
            });
        } catch (error) {
            toast({
                title: "Error",
                description: "Failed to generate estimate. Please try again.",
                variant: "destructive"
            });
        } finally {
            setLoading(false);
        }
    };

    const reset = () => {
        setStep(1);
        setStrategy(null);
        setFormData({ infrastructure: "", users: "", dataVolume: "", industry: "", email: "" });
    }

    return (
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogTrigger asChild>
                <Button variant="outline" className="px-8 py-4 rounded-xl text-lg font-semibold w-full sm:w-auto hover:bg-primary/10 border-primary/20 text-foreground">
                    Get AI Strategy Estimate
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[600px] glass-intense border-primary/20 max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="text-2xl font-display font-bold text-center mb-2">
                        AI Implementation Estimator
                    </DialogTitle>
                    <p className="text-center text-muted-foreground text-sm">
                        Powered by Google Gemini 2.5 Flash
                    </p>
                </DialogHeader>

                {step === 1 ? (
                    <div className="space-y-4 py-4">
                        <div className="space-y-2">
                            <Label>Current Infrastructure</Label>
                            <Select onValueChange={(val) => setFormData({ ...formData, infrastructure: val })}>
                                <SelectTrigger>
                                    <SelectValue placeholder="Select type" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="on-prem">On-Premise Legacy</SelectItem>
                                    <SelectItem value="hybrid">Hybrid Cloud</SelectItem>
                                    <SelectItem value="cloud-native">Cloud Native</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-2">
                            <Label>Data Volume (Monthly)</Label>
                            <Select onValueChange={(val) => setFormData({ ...formData, dataVolume: val })}>
                                <SelectTrigger>
                                    <SelectValue placeholder="Select volume" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="low">Under 1TB</SelectItem>
                                    <SelectItem value="med">1TB - 50TB</SelectItem>
                                    <SelectItem value="high">50TB+ (Big Data)</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-2">
                            <Label>Industry Sector</Label>
                            <Select onValueChange={(val) => setFormData({ ...formData, industry: val })}>
                                <SelectTrigger>
                                    <SelectValue placeholder="Select industry" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="finance">Finance & Banking</SelectItem>
                                    <SelectItem value="healthcare">Healthcare</SelectItem>
                                    <SelectItem value="retail">Retail & E-commerce</SelectItem>
                                    <SelectItem value="manufacturing">Manufacturing</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <Button
                            className="w-full btn-primary mt-4"
                            onClick={handleEstimate}
                            disabled={!formData.infrastructure || !formData.dataVolume || !formData.industry || loading}
                        >
                            {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : "Generate 2026 Strategy"}
                        </Button>
                    </div>
                ) : (
                    <div className="py-2 space-y-6">
                        <div className="text-center">
                            <div className="w-12 h-12 bg-green-500/10 rounded-full flex items-center justify-center mx-auto mb-3">
                                <CheckCircle className="w-6 h-6 text-green-500" />
                            </div>
                            <h3 className="text-xl font-bold mb-1">Strategy Generated</h3>
                            <p className="text-xs text-muted-foreground">{formData.industry} • {formData.infrastructure}</p>
                        </div>

                        {strategy && (
                            <div className="space-y-4">
                                <div className="bg-white/5 p-4 rounded-lg border border-white/10">
                                    <h4 className="text-sm font-bold text-primary mb-2">Executive Summary</h4>
                                    <p className="text-sm text-gray-300 leading-relaxed">{strategy.executiveSummary}</p>
                                </div>

                                <div className="grid grid-cols-2 gap-4">
                                    <div className="bg-white/5 p-3 rounded-lg border border-white/10">
                                        <h4 className="text-xs font-bold text-green-400 mb-1">Projected ROI</h4>
                                        <p className="text-sm font-semibold">{strategy.roiProjection}</p>
                                    </div>
                                    <div className="bg-white/5 p-3 rounded-lg border border-white/10">
                                        <h4 className="text-xs font-bold text-red-400 mb-1">Key Risk</h4>
                                        <p className="text-xs text-gray-300 line-clamp-3">{strategy.riskAssessment}</p>
                                    </div>
                                </div>

                                <div>
                                    <h4 className="text-sm font-bold mb-2">Implementation Roadmap</h4>
                                    <div className="space-y-2">
                                        {strategy.roadmap?.map((step: any, idx: number) => (
                                            <div key={idx} className="flex gap-3 text-sm bg-secondary/20 p-2 rounded">
                                                <span className="font-mono text-xs text-primary bg-primary/10 px-1 py-0.5 rounded h-fit whitespace-nowrap">{step.timeline}</span>
                                                <div>
                                                    <p className="font-bold text-xs">{step.phase}</p>
                                                    <p className="text-xs text-gray-400">{step.action}</p>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>

                                <div>
                                    <h4 className="text-sm font-bold mb-2">Compliance Requirements</h4>
                                    <div className="flex flex-wrap gap-2">
                                        {strategy.complianceChecklist?.map((item: string, idx: number) => (
                                            <span key={idx} className="text-xs bg-white/5 border border-white/10 px-2 py-1 rounded-full text-gray-300">
                                                {item}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        )}

                        <Button className="w-full btn-primary" onClick={() => { setIsOpen(false); reset(); }}>
                            Close Report
                        </Button>
                    </div>
                )}
            </DialogContent>
        </Dialog>
    );
}
